"""add ai_prompts table

Revision ID: 6f23cc1be5af
Revises: 984823b96c68
Create Date: 2026-07-28 12:27:06.593869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f23cc1be5af'
down_revision: Union[str, None] = '984823b96c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompts',
    sa.Column('uid', mysql.CHAR(length=36), nullable=False),
    sa.Column('prompt_key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt_name', sa.String(length=180), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capability', sa.String(length=80), nullable=True),
    sa.Column('provider_name', sa.String(length=60), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('prompt', mysql.LONGTEXT(), nullable=False),
    sa.Column('prompt_response_format', sa.String(length=40), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('variables_json', mysql.JSON(), nullable=True),
    sa.Column('variables_schema_json', mysql.JSON(), nullable=True),
    sa.Column('response_schema_json', mysql.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=180), nullable=True),
    sa.Column('updated_by', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('prompt_key', 'version', name='uq_ai_prompts_key_version'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ai_prompts_capability', 'ai_prompts', ['capability'], unique=False)
    op.create_index('ix_ai_prompts_is_active', 'ai_prompts', ['is_active'], unique=False)
    op.create_index('ix_ai_prompts_provider_name', 'ai_prompts', ['provider_name'], unique=False)
    op.create_index('ix_ai_prompts_status', 'ai_prompts', ['status'], unique=False)
    op.alter_column('adm_assessment_session', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('draft', 'submitted', 'cancelled', 'expired', name='sessionstatus', native_enum=False, length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adm_assessment_session', 'status',
               existing_type=sa.Enum('draft', 'submitted', 'cancelled', 'expired', name='sessionstatus', native_enum=False, length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('ix_ai_prompts_status', table_name='ai_prompts')
    op.drop_index('ix_ai_prompts_provider_name', table_name='ai_prompts')
    op.drop_index('ix_ai_prompts_is_active', table_name='ai_prompts')
    op.drop_index('ix_ai_prompts_capability', table_name='ai_prompts')
    op.drop_table('ai_prompts')
    # ### end Alembic commands ###
