"""initial tables

Revision ID: 984823b96c68
Revises: 
Create Date: 2026-07-04 13:57:24.616247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '984823b96c68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_assessment_question',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('question_ref', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_description', sa.Text(), nullable=True),
    sa.Column('section_key', sa.String(length=100), nullable=False),
    sa.Column('subsection_key', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('answer_type', sa.String(length=50), nullable=False),
    sa.Column('answer_condition', sa.String(length=255), nullable=True),
    sa.Column('answer_options_json', mysql.JSON(), nullable=True),
    sa.Column('answer_unit_json', mysql.JSON(), nullable=True),
    sa.Column('dependency_json', mysql.JSON(), nullable=True),
    sa.Column('input_placeholder', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('validation_rules_json', mysql.JSON(), nullable=True),
    sa.Column('visibility_condition_json', mysql.JSON(), nullable=True),
    sa.Column('default_value_json', mysql.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('score_weight', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_adm_assessment_question_question_ref'), 'adm_assessment_question', ['question_ref'], unique=True)
    op.create_index(op.f('ix_adm_assessment_question_section_key'), 'adm_assessment_question', ['section_key'], unique=False)
    op.create_index(op.f('ix_adm_assessment_question_subsection_key'), 'adm_assessment_question', ['subsection_key'], unique=False)
    op.create_index('ix_section_subsection_order', 'adm_assessment_question', ['section_key', 'subsection_key', 'display_order'], unique=False)
    op.create_table('adm_assessment_session',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('customer_uid', sa.String(length=36), nullable=False),
    sa.Column('company_uid', sa.String(length=36), nullable=True),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('completed_steps_json', mysql.JSON(), nullable=True),
    sa.Column('metadata_json', mysql.JSON(), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_adm_assessment_session_assessment_type'), 'adm_assessment_session', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_adm_assessment_session_company_uid'), 'adm_assessment_session', ['company_uid'], unique=False)
    op.create_index(op.f('ix_adm_assessment_session_customer_uid'), 'adm_assessment_session', ['customer_uid'], unique=False)
    op.create_index(op.f('ix_adm_assessment_session_status'), 'adm_assessment_session', ['status'], unique=False)
    op.create_index('ix_company_status', 'adm_assessment_session', ['company_uid', 'status'], unique=False)
    op.create_index('ix_customer_status', 'adm_assessment_session', ['customer_uid', 'status'], unique=False)
    op.create_table('adm_assessment_answer',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('session_uid', sa.String(length=36), nullable=False),
    sa.Column('question_uid', sa.String(length=36), nullable=False),
    sa.Column('answer_type', sa.String(length=50), nullable=True),
    sa.Column('answer_unit', sa.String(length=50), nullable=True),
    sa.Column('response_string', sa.Text(), nullable=True),
    sa.Column('response_number', sa.Float(), nullable=True),
    sa.Column('response_boolean', sa.Boolean(), nullable=True),
    sa.Column('response_list_json', mysql.JSON(), nullable=True),
    sa.Column('response_object_json', mysql.JSON(), nullable=True),
    sa.Column('answer_qualifier', sa.String(length=100), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_uid'], ['adm_assessment_question.uid'], ),
    sa.ForeignKeyConstraint(['session_uid'], ['adm_assessment_session.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('session_uid', 'question_uid', name='uq_session_question'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adm_assessment_answer')
    op.drop_index('ix_customer_status', table_name='adm_assessment_session')
    op.drop_index('ix_company_status', table_name='adm_assessment_session')
    op.drop_index(op.f('ix_adm_assessment_session_status'), table_name='adm_assessment_session')
    op.drop_index(op.f('ix_adm_assessment_session_customer_uid'), table_name='adm_assessment_session')
    op.drop_index(op.f('ix_adm_assessment_session_company_uid'), table_name='adm_assessment_session')
    op.drop_index(op.f('ix_adm_assessment_session_assessment_type'), table_name='adm_assessment_session')
    op.drop_table('adm_assessment_session')
    op.drop_index('ix_section_subsection_order', table_name='adm_assessment_question')
    op.drop_index(op.f('ix_adm_assessment_question_subsection_key'), table_name='adm_assessment_question')
    op.drop_index(op.f('ix_adm_assessment_question_section_key'), table_name='adm_assessment_question')
    op.drop_index(op.f('ix_adm_assessment_question_question_ref'), table_name='adm_assessment_question')
    op.drop_table('adm_assessment_question')
    # ### end Alembic commands ###
