
from datetime import datetime, timezone

from app.models.database import SessionLocal  
from app.models.adm_assessment_question import AdmAssessmentQuestion


SEED_QUESTIONS = [
    {
        'uid': 'ff95ab48-5bba-4133-846e-f8ec1e05c298',
        'question_ref': 'GEN-001',
        'question_text': 'What is your current annual Application Delivery Management budget?',
        'question_description': 'Include software licences, maintenance, infrastructure, managed services, external services, and internal FTE costs.',
        'section_key': 'general_information',
        'subsection_key': 'scope_and_costs',
        'display_order': 10,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': ['EUR'],
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '4b903961-2be9-4836-a93c-ebd88f90469b',
        'question_ref': 'GEN-002',
        'question_text': 'How many FTEs are involved in application delivery activities?',
        'question_description': 'Include developers, testers, business analysts, DevOps engineers, release managers, project managers, and application support teams.',
        'section_key': 'general_information',
        'subsection_key': 'scope_and_resources',
        'display_order': 20,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '7affa1a0-4ae4-454f-828e-c4cc96ad087e',
        'question_ref': 'GEN-003',
        'question_text': 'How many external FTEs are involved in application delivery?',
        'question_description': 'Include consultants, contractors, service providers, nearshore teams, and offshore teams.',
        'section_key': 'general_information',
        'subsection_key': 'scope_and_resources',
        'display_order': 30,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '319eb1fd-ac04-49f1-9e7d-e2638e416289',
        'question_ref': 'GEN-004',
        'question_text': 'How many applications are included in the ADM scope?',
        'question_description': 'Include applications currently managed and applications planned to be managed through the ADM solution.',
        'section_key': 'general_information',
        'subsection_key': 'application_portfolio',
        'display_order': 40,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'e6b45486-5505-4223-b2a2-13a2bac532a8',
        'question_ref': 'GEN-005',
        'question_text': 'How many business-critical applications are included in the ADM scope?',
        'question_description': 'A business-critical application directly affects revenue, customers, operations, regulatory obligations, or essential business services.',
        'section_key': 'general_information',
        'subsection_key': 'application_portfolio',
        'display_order': 50,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'c4fb6903-a73c-452d-a12b-295ea4ac3801',
        'question_ref': 'GEN-006',
        'question_text': 'What is the average lead time from an approved request to production delivery?',
        'question_description': 'Measure the time between approval of a business request and its production deployment.',
        'section_key': 'general_information',
        'subsection_key': 'delivery_performance',
        'display_order': 60,
        'answer_type': 'select',
        'answer_options_json': ['Less than one week', '1–4 weeks', '1–3 months', '3–6 months', 'More than six months', 'Not measured'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '6d85cfb7-009e-4343-a229-c682a0664cf2',
        'question_ref': 'GEN-007',
        'question_text': 'How many production releases were completed during the last 12 months?',
        'question_description': 'If the exact number is unavailable, an approximate value may be provided.',
        'section_key': 'general_information',
        'subsection_key': 'delivery_performance',
        'display_order': 70,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'd6836391-ecf6-4394-8b11-ebac7705aac8',
        'question_ref': 'GEN-008',
        'question_text': 'How many application defects or release-related incidents occurred during the last 12 months?',
        'question_description': 'Include functional defects, regressions, failed deployments, performance issues, and release failures.',
        'section_key': 'general_information',
        'subsection_key': 'quality_and_incidents',
        'display_order': 80,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '356fde98-fdd1-4a1f-9029-b6dcc9372415',
        'question_ref': 'GEN-009',
        'question_text': 'How many P1 or business-critical incidents were caused by application changes during the last 12 months?',
        'question_description': 'If the exact number is unavailable, an approximate value may be provided.',
        'section_key': 'general_information',
        'subsection_key': 'quality_and_incidents',
        'display_order': 90,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'd6c93258-f35f-4a56-a75c-197afde78702',
        'question_ref': 'GEN-010',
        'question_text': 'Which application delivery KPIs are currently measured?',
        'question_description': 'Select all ADM performance indicators currently measured.',
        'section_key': 'general_information',
        'subsection_key': 'kpis',
        'display_order': 100,
        'answer_type': 'multi_select',
        'answer_options_json': [
  "Deployment frequency",
  "Delivery lead time",
  "Release success rate",
  "Change failure rate",
  "Defect escape rate",
  "Test automation coverage",
  "Requirements coverage",
  "Mean time to restore",
  "Rework rate",
  "Development productivity",
  "Customer satisfaction",
  "Error rate",
  "Security vulnerability count",
  "Infrastructure availability",
  "Lead time to value",
  "Feature adoption rate",
  "Cost per transaction",
  "SLO compliance",
  "Application latency",
  "Pipeline execution time",
  "Technical debt ratio",
  "Mean time to remediate vulnerabilities",
  "No ADM KPIs are currently measured"
],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '7cee8996-f273-4cf1-9a39-85df6ccb04c6',
        'question_ref': 'ADM-001',
        'question_text': 'Which tools are used to manage application delivery?',
        'question_description': 'Include tools used from business request and requirements through development, testing, and release.',
        'section_key': 'adm_information',
        'subsection_key': 'application_and_project_management',
        'display_order': 10,
        'answer_type': 'multi_select',
        'answer_options_json': ['OpenText Software Delivery Management', 'Jira', 'Azure DevOps', 'GitLab', 'IBM Engineering Lifecycle Management', 'ServiceNow', 'OpenText ALM / Quality Center', 'In-house developed solution', 'Spreadsheets', 'No dedicated solution','Polarion ALM','Rally (Broadcom Agile Central)'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '8b560cd9-e45c-43b3-8b39-157baabc1d8d',
        'question_ref': 'ADM-002',
        'question_text': 'How many applications are currently managed through your ADM tools?',
        'question_description': 'Enter the total number of applications currently covered by ADM tooling.',
        'section_key': 'adm_information',
        'subsection_key': 'application_and_project_management',
        'display_order': 20,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '38eedba2-c72d-49be-b5f8-bae6a5d75e5e',
        'question_ref': 'ADM-003',
        'question_text': 'How is ADM tool coverage distributed across your application portfolio?',
        'question_description': 'For each ADM solution, provide the approximate number and percentage of applications managed.',
        'section_key': 'adm_information',
        'subsection_key': 'application_and_project_management',
        'display_order': 30,
        'answer_type': 'multi_select',
        'answer_options_json': ['tool', 'number of applications', 'portfolio percentage'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'd05072fb-9171-4817-b987-f31537d46d77',
        'question_ref': 'ADM-004',
        'question_text': 'Which activities are covered by your ADM solution?',
        'question_description': 'Select all application delivery activities currently supported.',
        'section_key': 'adm_information',
        'subsection_key': 'application_and_project_management',
        'display_order': 40,
        'answer_type': 'multi_select',
        'answer_options_json': [
    "Demand management",
    "Requirements management",
    "Portfolio management",
    "Backlog management",
    "Project planning",
    "Source-code management",
    "Build management",
    "Test management",
    "Defect management",
    "Release management",
    "Deployment management",
    "Application security testing",
    "Vulnerability and License compliance management",
    "Environment and Test Data management",
    "Incident and problem management",
    "Application performance monitoring and Observability",
    "Value Stream Management",
    " Cloud cost optimization",
    "Reporting and dashboards",
    "End-to-end traceability"
  ],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '54b315e8-affb-46aa-8f7d-aad5f13f9e03',
        'question_ref': 'ADM-005',
        'question_text': 'Which development methodologies are used?',
        'question_description': 'Select all methodologies actively used by delivery teams.',
        'section_key': 'adm_information',
        'subsection_key': 'application_and_project_management',
        'display_order': 50,
        'answer_type': 'multi_select',
        'answer_options_json': ['Scrum', 'Kanban', 'SAFe', 'Waterfall', 'V-Model', 'Hybrid', 'DevOps','Extreme Programming (XP)','Lean Software Development','Feature-Driven Development (FDD)','Scrumban', 'No formally defined methodology',],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '3e5c7062-14a1-4f1e-ac88-9fff7768fefa',
        'question_ref': 'ADM-006',
        'question_text': 'How are business and technical requirements managed?',
        'question_description': 'Select the approach that best represents the current requirements-management process.',
        'section_key': 'adm_information',
        'subsection_key': 'requirements_management',
        'display_order': 60,
        'answer_type': 'select',
        'answer_options_json': [
    "Centrally in a dedicated requirements-management tool",
    "In the main project-management tool",
    "Across several integrated tools",
    "Through documents or spreadsheets",
    "Managed as user stories within team-level agile backlogs",
    "Managed as code or text files within source repository (Docs-as-Code)",
    "In collaborative workspaces and visual wikis",
    "Managed directly inside test-management and BDD tools",
    "Through a hybrid approach based on project criticality",
    "Managed and tracked through AI-assisted requirement platforms",
    "Requirements are not formally managed"
  ],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'c0cb770c-b50c-4d6b-9339-47b16714764f',
        'question_ref': 'ADM-007',
        'question_text': 'Which tools are used for requirements and demand management?',
        'question_description': 'Select all tools used to capture and manage business or technical requirements.',
        'section_key': 'adm_information',
        'subsection_key': 'requirements_management',
        'display_order': 70,
        'answer_type': 'multi_select',
        'answer_options_json': ['OpenText Software Delivery Management', 'Jira', 'Azure DevOps', 'IBM DOORS', 'ServiceNow', 'Confluence', 'Spreadsheets', 'In-house solution', 'No dedicated tool', 'Other'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '3229f196-3f91-48ea-bd44-cf68a54b53dd',
        'question_ref': 'ADM-008',
        'question_text': 'Can requirements be traced from the initial request through development, testing, and production release?',
        'question_description': 'Evaluate the level of end-to-end delivery traceability.',
        'section_key': 'adm_information',
        'subsection_key': 'requirements_management',
        'display_order': 80,
        'answer_type': 'select',
        'answer_options_json': ['Yes, complete end-to-end traceability', 'Partially', 'Only between some delivery stages', 'No', 'Not measured'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'd1c698e7-749e-4ac2-b1fb-b9e3b8cfa35f',
        'question_ref': 'ADM-009',
        'question_text': 'Which source-code management platforms are used?',
        'question_description': 'Select all source-code repositories currently used.',
        'section_key': 'adm_information',
        'subsection_key': 'source_code_and_development_management',
        'display_order': 90,
        'answer_type': 'multi_select',
        'answer_options_json': ['GitLab', 'GitHub', 'Bitbucket', 'Azure Repos', 'Subversion', 'IBM Rational ClearCase', 'In-house solution','Perforce Helix Core', 'Gitea','Forgejo',],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '7108e6e7-6a00-467d-b245-371f5502c2a2',
        'question_ref': 'ADM-010',
        'question_text': 'Which development practices are currently used?',
        'question_description': 'Select all practices consistently applied by development teams.',
        'section_key': 'adm_information',
        'subsection_key': 'source_code_and_development_management',
        'display_order': 100,
        'answer_type': 'multi_select',
        'answer_options_json': [
    "Code reviews",
    "Pull or merge requests",
    "Branching strategy",
    "Trunk-based development",
    "Static code analysis (SAST)",
    "Dynamic application security testing (DAST)",
    "Coding standards",
    "Pair programming",
    "Dependency management",
    "Software composition analysis (SCA)",
    "Secrets scanning",
    "Software supply chain security / Artifact signing",
    "Peer approval before merging",
    "Feature toggles / Feature flagging",
    "Continuous Integration / Continuous Delivery (CI/CD)",
    "Infrastructure as Code (IaC)",
    "GitOps",
    "AI-assisted coding / AI Copilots",
    "Test-driven development (TDD) / BDD",
    "InnerSourcing",
    "None"
  ],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '86c9972b-b5c4-4e2f-8f34-9db450ae3a3a',
        'question_ref': 'ADM-011',
        'question_text': 'Which code-quality and static-analysis tools are used?',
        'question_description': 'Select all code-quality, security, and static-analysis tools currently used.',
        'section_key': 'adm_information',
        'subsection_key': 'source_code_and_development_management',
        'display_order': 110,
        'answer_type': 'multi_select',
        'answer_options_json': [
  'SonarQube',
  'SonarCloud',
  'OpenText Fortify',
  'Checkmarx',
  'Veracode',
  'Coverity',
  'CodeQL / GitHub Advanced Security',
  'Semgrep',
  'Snyk Code',
  'Codacy',
  'DeepSource',
  'Qodana',
  'Klocwork',
  'Code Climate',
  'ESLint',
  'PMD',
  'Ruff / Flake8 / Pylint',
  'RuboCop',
  'golangci-lint',
  'Clippy',
  'Roslyn Analyzers',
  'Checkov / Tfsec',
  'In-house tools',
  'No code-quality tool',
],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '5a6ad1ce-1245-424d-a7bc-a63f79f5ea48',
        'question_ref': 'ADM-012',
        'question_text': 'Has your application portfolio experienced functional issues in production?',
        'question_description': 'Include bugs, regressions, incorrect results, failed integrations, or unavailable functionality.',
        'section_key': 'adm_information',
        'subsection_key': 'functional_testing',
        'display_order': 120,
        'answer_type': 'select',
        'answer_options_json': ['Never', 'Rarely', 'Sometimes, with limited impact', 'Frequently, with limited impact', 'Yes, with significant user or business impact'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '86b5ca2c-e661-4e70-a355-1449d3165ee7',
        'question_ref': 'ADM-013',
        'question_text': 'How frequently is functional testing performed?',
        'question_description': 'Select the frequency that best represents the current testing practice.',
        'section_key': 'adm_information',
        'subsection_key': 'functional_testing',
        'display_order': 130,
        'answer_type': 'select',
        'answer_options_json': ['For every application change', 'For every release', 'For major releases only', 'Occasionally', 'Only after a production incident', 'Never'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '7f8a5de6-be69-4601-8a74-08bb190e5d1b',
        'question_ref': 'ADM-014',
        'question_text': 'How are functional tests performed?',
        'question_description': 'Specify the current execution approach.',
        'section_key': 'adm_information',
        'subsection_key': 'functional_testing',
        'display_order': 140,
        'answer_type': 'select',
        'answer_options_json': ['Manually', 'Automatically', 'Both manually and automatically', 'Functional testing is not performed'],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'visibility_condition_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '56fcda22-a5cd-49ce-9e93-428141c5bce3',
        'question_ref': 'ADM-015',
        'question_text': 'Which functional testing tools are used?',
        'question_description': 'Select all tools used for UI, API, mobile, or regression functional testing.',
        'section_key': 'adm_information',
        'subsection_key': 'functional_testing',
        'display_order': 150,
        'answer_type': 'select',
        'answer_options_json': [
            'Selenium',
            'Cypress',
            'Playwright',
            'WebdriverIO',
            'Puppeteer',
            'OpenText Functional Testing',
            'TestComplete',
            'Tricentis Tosca',
            'Katalon Studio',
            'Postman',
            'REST Assured',
            'Karate Framework',
            'SoapUI',
            'Appium',
            'Espresso',
            'XCUITest',
            'Robot Framework',
            'Cucumber',
            'In-house solution',
            'No functional testing tool',
        ],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'visibility_condition_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '2961e107-31d3-4ba7-95f6-810de02ede0f',
        'question_ref': 'ADM-016',
        'question_text': 'What percentage of functional regression tests is automated?',
        'question_description': 'Estimate the proportion of the regression test suite currently automated.',
        'section_key': 'adm_information',
        'subsection_key': 'functional_testing',
        'display_order': 160,
        'answer_type': 'select',
        'answer_options_json': ['0%', '1–25%', '26–50%', '51–75%', '76–90%', 'More than 90%', 'Unknown'],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'visibility_condition_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '61b526e9-4090-4f53-89e6-2aba0ca0ae0f',
        'question_ref': 'ADM-017',
        'question_text': 'Which tools are used to manage test cases, test execution, and test results?',
        'question_description': 'Select all test-management tools currently used.',
        'section_key': 'adm_information',
        'subsection_key': 'functional_testing',
        'display_order': 170,
        'answer_type': 'select',
        'answer_options_json': [
  'OpenText ALM / Quality Center',
  'OpenText Software Delivery Management',
  'Jira with test-management plugin',
  'Xray',
  'Zephyr',
  'QMetry',
  'AIO Tests',
  'Azure Test Plans',
  'TestRail',
  'PractiTest',
  'Qase',
  'Testmo',
  'qTest',
  'TestLink',
  'SpiraTest (Inflectra)',
  'Kualitee',
  'IBM Engineering Test Management (RQM)',
  'Spreadsheets',
  'In-house tools',
  'No dedicated tool',
  
],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'visibility_condition_json': {'question_ref': 'ADM-013', 'operator': 'not_equals', 'value': 'Never'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '58bb1c00-140d-4de6-8899-30a2b21a15c2',
        'question_ref': 'ADM-018',
        'question_text': 'How are defects managed?',
        'question_description': 'Select the approach that best represents the current defect-management process.',
        'section_key': 'adm_information',
        'subsection_key': 'functional_testing',
        'display_order': 180,
        'answer_type': 'select',
        'answer_options_json': ['Centrally in one shared tool', 'Across multiple integrated tools', 'Across multiple non-integrated tools', 'Through email or spreadsheets', 'No formally defined defect-management process'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'e38e4169-de85-432f-aafe-7a4db3bd3b63',
        'question_ref': 'ADM-019',
        'question_text': 'Has your application portfolio experienced performance degradation or outages during traffic peaks?',
        'question_description': 'Consider peak periods such as sales events, campaigns, or seasonal traffic.',
        'section_key': 'adm_information',
        'subsection_key': 'performance_testing',
        'display_order': 190,
        'answer_type': 'select',
        'answer_options_json': ['Never', 'Rarely', 'Sometimes, with limited impact', 'Frequently', 'Yes, with significant impact on users, operations, or revenue'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '92cab1ba-d444-401b-b48c-627d482dd802',
        'question_ref': 'ADM-020',
        'question_text': 'How frequently are load and performance tests performed?',
        'question_description': 'Select the frequency that best represents current performance-testing practices.',
        'section_key': 'adm_information',
        'subsection_key': 'performance_testing',
        'display_order': 200,
        'answer_type': 'select',
        'answer_options_json': ['For every major change', 'For every release', 'For major releases only', 'Occasionally', 'Only after a production incident', 'Never'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'df023230-ac7c-4075-935e-9f97ffb48129',
        'question_ref': 'ADM-021',
        'question_text': 'How are performance tests performed?',
        'question_description': 'Specify the current execution approach.',
        'section_key': 'adm_information',
        'subsection_key': 'performance_testing',
        'display_order': 210,
        'answer_type': 'select',
        'answer_options_json': ['Manually', 'Automatically', 'Both manually and automatically', 'Performance testing is not performed'],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-020', 'operator': 'not_equals', 'value': 'Never'},
        'visibility_condition_json': {'question_ref': 'ADM-020', 'operator': 'not_equals', 'value': 'Never'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '892d986e-d391-4043-9c05-53c6a69d626f',
        'question_ref': 'ADM-022',
        'question_text': 'Which performance testing tools are used?',
        'question_description': 'Select all load and performance testing tools currently used.',
        'section_key': 'adm_information',
        'subsection_key': 'performance_testing',
        'display_order': 220,
        'answer_type': 'select',
        'answer_options_json': [
            'OpenText Performance Engineering / LoadRunner',
            'Apache JMeter',
            'k6',
            'NeoLoad',
            'Gatling',
            'BlazeMeter',
            'Locust',
            'Artillery',
            'LoadNinja',
            'WebLOAD',
            'OctoPerf',
            'ApacheBench (ab) / Siege / wrk',
            'Loadster',
            'Vegeta',
            'Tsung',
            'HammerDB',
            'In-house solution',
            'No performance testing tool',
        ],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-020', 'operator': 'not_equals', 'value': 'Never'},
        'visibility_condition_json': {'question_ref': 'ADM-020', 'operator': 'not_equals', 'value': 'Never'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '0842a135-bcbb-4360-814f-6374eeb860bb',
        'question_ref': 'ADM-023',
        'question_text': 'Do performance tests reproduce real-user traffic patterns and load distribution?',
        'question_description': 'Indicate whether production traffic data or representative estimates are used.',
        'section_key': 'adm_information',
        'subsection_key': 'performance_testing',
        'display_order': 230,
        'answer_type': 'select',
        'answer_options_json': ['Yes, based on production data', 'Partially', 'Based on estimates only', 'No', 'Not applicable'],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-020', 'operator': 'not_equals', 'value': 'Never'},
        'visibility_condition_json': {'question_ref': 'ADM-020', 'operator': 'not_equals', 'value': 'Never'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'e2afa2bb-4086-4d5d-ac52-2ede571717b9',
        'question_ref': 'ADM-024',
        'question_text': 'Do you use CI/CD pipelines?',
        'question_description': 'Indicate the level of CI/CD adoption across the application portfolio.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 240,
        'answer_type': 'select',
        'answer_options_json': ['Yes, for all applications', 'Yes, for most applications', 'Yes, for selected applications', 'Planned', 'No'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '9fda7e72-1933-449b-ab46-10343aec7acc',
        'question_ref': 'ADM-025',
        'question_text': 'Which CI/CD platforms are used?',
        'question_description': 'Select all platforms used to build, test, and deploy applications.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 250,
        'answer_type': 'multi_select',
        'answer_options_json': [
  'Jenkins',
  'GitLab CI/CD',
  'Azure DevOps',
  'GitHub Actions',
  'Bamboo',
  'TeamCity',
  'OpenText Deployment Automation',
  'CircleCI',
  'Travis CI',
  'Argo CD / Argo Workflows',
  'Flux CD',
  'Tekton',
  'Octopus Deploy',
  'Harness',
  'Spinnaker',
  'AWS CodePipeline / CodeBuild',
  'Google Cloud Build',
  'Buildkite',
  'Drone CI',
  'Concourse CI',
  'In-house solution',
  'No CI/CD platform',
],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'visibility_condition_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '16217a90-394a-4a46-a637-1c4c47f961a5',
        'question_ref': 'ADM-026',
        'question_text': 'How many applications are currently integrated into CI/CD pipelines?',
        'question_description': 'Enter the total number of applications currently covered by CI/CD.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 260,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'visibility_condition_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '061dbeba-7d04-4075-9bc9-a290ef413533',
        'question_ref': 'ADM-027',
        'question_text': 'Which activities are automated in your CI/CD pipelines?',
        'question_description': 'Select all automated activities.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 270,
        'answer_type': 'multi_select',
        'answer_options_json': [
    "Compilation and build",
    "Unit testing",
    "Code-quality analysis",
    "Functional testing",
    "API testing",
    "Performance testing",
    "Security testing (SAST/DAST)",
    "Secrets scanning",
    "Software composition analysis (SCA) & License checking",
    "Container and image scanning",
    "Software Bill of Materials (SBOM) generation & Artifact signing",
    "Package creation & Artifact publishing",
    "Environment provisioning",
    "Infrastructure-as-Code compliance & security linting",
    "Deployment",
    "Database deployment & Schema migrations",
    "Automated progressive delivery (Canary / Blue-Green)",
    "Rollback",
    "Automated rollback triggering (via SLO/Metrics thresholds)",
    "Production validation & Smoke testing",
    "Drift detection",
    "Automated release notes & Changelog generation",
    "Ticket status update and traceability logging",
    "None"
  ],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'visibility_condition_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '32d3cac2-0d48-4501-85ad-c295c946834d',
        'question_ref': 'ADM-028',
        'question_text': 'Are automated quality gates used before changes can progress through the delivery pipeline?',
        'question_description': 'Quality gates may include test success, coverage thresholds, code quality, security, or approvals.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 280,
        'answer_type': 'select',
        'answer_options_json': ['Yes, across all applications', 'Yes, for selected applications', 'Partially', 'No', 'Planned'],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-024', 'operator': 'not_equals', 'value': 'No'},
        'visibility_condition_json': {'question_ref': 'ADM-024', 'operator': 'not_equals', 'value': 'No'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'e97135ba-cc36-4ad1-ba59-b2a723cb59f1',
        'question_ref': 'ADM-029',
        'question_text': 'Are performance tests integrated into CI/CD pipelines?',
        'question_description': 'Evaluate the level of automated performance testing in the pipeline.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 290,
        'answer_type': 'select',
        'answer_options_json': ['Fully integrated', 'Integrated for selected applications', 'Partially integrated', 'No', 'Not applicable'],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'visibility_condition_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '27115057-d19f-404b-9d90-0708b56cb954',
        'question_ref': 'ADM-030',
        'question_text': 'Are automated functional tests integrated into CI/CD pipelines?',
        'question_description': 'Evaluate the level of automated functional testing in the pipeline.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 300,
        'answer_type': 'select',
        'answer_options_json': ['Fully integrated', 'Integrated for selected applications', 'Partially integrated', 'No', 'Not applicable'],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'visibility_condition_json': {'question_ref': 'ADM-024', 'operator': 'not_in', 'value': ['No', 'Planned']},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '7814a99a-069d-4cee-be0f-7cd597042cb3',
        'question_ref': 'ADM-031',
        'question_text': 'At which stages are testing and quality controls performed?',
        'question_description': 'Select all stages where formal testing or quality controls are applied.',
        'section_key': 'adm_information',
        'subsection_key': 'ci_cd_and_automation',
        'display_order': 310,
        'answer_type': 'multi_select',
        'answer_options_json': ['During requirements definition', 'During development', 'During code integration', 'Before production release', 'After deployment', 'After a production incident', 'No formally defined testing stage'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '412f5498-b2f7-4150-b723-9918cd6a9560',
        'question_ref': 'ADM-032',
        'question_text': 'How frequently are applications released to production?',
        'question_description': 'Select the frequency that best represents the application portfolio.',
        'section_key': 'adm_information',
        'subsection_key': 'release_and_deployment_management',
        'display_order': 320,
        'answer_type': 'select',
        'answer_options_json': ['Multiple times per day', 'Daily', 'Weekly', 'Monthly', 'Quarterly', 'Less frequently', 'Depends on the application'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '41e5a323-f241-41dc-af17-b9b4e4ba7e3e',
        'question_ref': 'ADM-033',
        'question_text': 'How are production deployments performed?',
        'question_description': 'Evaluate the level of deployment automation.',
        'section_key': 'adm_information',
        'subsection_key': 'release_and_deployment_management',
        'display_order': 330,
        'answer_type': 'select',
        'answer_options_json': ['Fully automated', 'Mostly automated', 'Semi-automated', 'Mainly manual', 'Fully manual'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'a4ad1e82-0a30-452c-804f-35de7387c5a8',
        'question_ref': 'ADM-034',
        'question_text': 'How are production releases approved?',
        'question_description': 'Select the primary release-approval approach.',
        'section_key': 'adm_information',
        'subsection_key': 'release_and_deployment_management',
        'display_order': 340,
        'answer_type': 'select',
        'answer_options_json': ['Automated approval based on quality gates', 'Formal approval workflow in a shared tool', 'Change Advisory Board approval', 'Manual approval through email or meetings', 'No formally defined approval process'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '44997b1b-fe6b-4456-9002-35abc0b18adb',
        'question_ref': 'ADM-035',
        'question_text': 'Is a rollback process available for failed deployments?',
        'question_description': 'Indicate whether rollback is defined, tested, and automated.',
        'section_key': 'adm_information',
        'subsection_key': 'release_and_deployment_management',
        'display_order': 350,
        'answer_type': 'select',
        'answer_options_json': ['Yes, fully automated', 'Yes, partially automated', 'Yes, manual', 'Defined but not regularly tested', 'No'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '2fd1b2d9-8533-4945-acb4-ed973f1dc3c5',
        'question_ref': 'ADM-036',
        'question_text': 'What percentage of production releases are completed without rollback, hotfix, or major incident?',
        'question_description': 'Estimate the current production release success rate.',
        'section_key': 'adm_information',
        'subsection_key': 'release_and_deployment_management',
        'display_order': 360,
        'answer_type': 'select',
        'answer_options_json': ['Less than 50%', '50–70%', '71–85%', '86–95%', 'More than 95%', 'Unknown'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '8145fa82-b726-4b38-b359-b2e9b494c040',
        'question_ref': 'ADM-037',
        'question_text': 'Which systems are integrated with your ADM platform?',
        'question_description': 'Select all systems integrated with ADM tools.',
        'section_key': 'adm_information',
        'subsection_key': 'adm_integrations',
        'display_order': 370,
        'answer_type': 'multi_select',
        'answer_options_json': [
  'Requirements Management tools',
  'Issue Tracking tools',
  'Source Code Management tools',
  'CI/CD Platforms',
  'Testing tools',
  'Security Testing tools',
  'Service Desk tools',
  'ITSM tools',
  'Monitoring tools',
  'Observability tools',
  'Configuration Management Database',
  'Enterprise Architecture tools',
  'Artifact Repository tools',
  'Project Management tools',
  'No integrations'
],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'e9c42407-f430-4e56-b391-adb107bbb31e',
        'question_ref': 'ADM-038',
        'question_text': 'How are ADM tools integrated?',
        'question_description': 'Select the primary integration methods used.',
        'section_key': 'adm_information',
        'subsection_key': 'adm_integrations',
        'display_order': 380,
        'answer_type': 'multi_select',
        'answer_options_json': ['Native integrations', 'APIs', 'Webhooks', 'Custom connectors', 'Manual file exchange', 'Tools are not integrated', 'Event-driven messaging (e.g., Kafka, RabbitMQ)','CLI automation',],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ADM-037', 'operator': 'not_includes', 'value': 'No integrations'},
        'visibility_condition_json': {'question_ref': 'ADM-037', 'operator': 'not_includes', 'value': 'No integrations'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '813ff451-63ba-4abf-803a-8eea629452bb',
        'question_ref': 'ADM-039',
        'question_text': 'Do delivery teams have a unified view of requirements, development, tests, defects, and releases?',
        'question_description': 'Evaluate whether delivery information is accessible through a shared or integrated view.',
        'section_key': 'adm_information',
        'subsection_key': 'adm_integrations',
        'display_order': 390,
        'answer_type': 'select',
        'answer_options_json': ['Yes, through one shared platform', 'Yes, through integrated platforms', 'Partially', 'No', 'Planned'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '30ce3deb-8b7f-46a9-a24a-4e63f888debc',
        'question_ref': 'ADM-040',
        'question_text': 'Which ADM reporting capabilities are used?',
        'question_description': 'Select all centralized reporting and dashboard capabilities currently used.',
        'section_key': 'adm_information',
        'subsection_key': 'adm_integrations',
        'display_order': 400,
        'answer_type': 'multi_select',
        'answer_options_json': [
  'Project progress',
  'Release readiness',
  'Requirements coverage',
  'Test coverage',
  'Defect trends',
  'Development productivity',
  'Pipeline status',
  'Quality-gate status',
  'Delivery lead time',
  'Release success rate',
  'Deployment frequency',
  'Change failure rate',
  'Application performance metrics',
  'Incident and operational metrics',
  'Security and vulnerability reporting',
  'Code quality metrics',
  'Technical debt reporting',
  'Resource utilization',
  'Portfolio-level dashboards',
  'Executive dashboards',
  'Custom reports',
  'Real-time dashboards',
  'Scheduled reports',
  'No centralized reporting',
  
],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '278a9fba-1d64-46a4-910d-0403daa9187c',
        'question_ref': 'ENV-001',
        'question_text': 'Where are the applications in the ADM scope hosted?',
        'question_description': 'Select all hosting models used by the applications in scope.',
        'section_key': 'environment_information',
        'subsection_key': 'hosting_and_architecture',
        'display_order': 10,
        'answer_type': 'multi_select',
        'answer_options_json': ['On-premises', 'Private cloud', 'Public cloud', 'Hybrid cloud', 'SaaS','PaaS / Serverless','Edge computing','Government cloud',''],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '18b03f1e-5f47-4e64-8b15-599c6365d5d6',
        'question_ref': 'ENV-002',
        'question_text': 'How are applications distributed across hosting models?',
        'question_description': 'For each hosting model, provide the number and percentage of applications.',
        'section_key': 'environment_information',
        'subsection_key': 'hosting_and_architecture',
        'display_order': 20,
        'answer_type': 'multi_select',
        'answer_options_json': ['hosting model', 'number of applications', 'portfoliopercentage'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '2ae57dcd-2f64-4d3d-bb4e-14a461bc1ddc',
        'question_ref': 'ENV-003',
        'question_text': 'Which application architectures are used?',
        'question_description': 'Select all architecture patterns used across the application portfolio.',
        'section_key': 'environment_information',
        'subsection_key': 'hosting_and_architecture',
        'display_order': 30,
        'answer_type': 'multi_select',
        'answer_options_json': ['Monolithic', 'Microservices', 'Service-oriented architecture', 'Event-driven architecture', 'Serverless', 'Container-based', 'Mainframe', 'Client-server', 'Hybrid', 'Other'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '6e2180fb-268d-487d-9c60-c28d8523ea2f',
        'question_ref': 'ENV-004',
        'question_text': 'Which application technologies and programming languages are used?',
        'question_description': 'Select all major technologies used by the applications in scope.',
        'section_key': 'environment_information',
        'subsection_key': 'hosting_and_architecture',
        'display_order': 40,
        'answer_type': 'multi_select',
        'answer_options_json': [
  'Java',
  '.NET / C#',
  'JavaScript',
  'TypeScript',
  'Python',
  'PHP',
  'Go',
  'C',
  'C++',
  'Rust',
  'Kotlin',
  'Swift',
  'Ruby',
  'SQL ',
  'Shell scripting (Bash, PowerShell)',
  'R',
  'MATLAB',
  ' No-code platforms',  
  
],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'fc73d423-5ef4-4bb8-a386-b8632ee08ee1',
        'question_ref': 'ENV-005',
        'question_text': 'Which application environments are available?',
        'question_description': 'Select all lifecycle environments currently available.',
        'section_key': 'environment_information',
        'subsection_key': 'application_environments',
        'display_order': 50,
        'answer_type': 'multi_select',
        'answer_options_json': ['Development', 'Testing', 'Integration', 'User acceptance testing', 'Performance testing', 'Security testing', 'Staging', 'Pre-production', 'Production', 'Disaster recovery', 'Other'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'd4f41919-c16f-42c6-bd88-7d3b089627a2',
        'question_ref': 'ENV-006',
        'question_text': 'How many applications or workloads are deployed in each environment?',
        'question_description': 'For each environment, provide the number of applications and the number of servers, containers, or workloads.',
        'section_key': 'environment_information',
        'subsection_key': 'application_environments',
        'display_order': 60,
        'answer_type': 'multi_select',
        'answer_options_json': ['environment', 'number of applications', 'number of workloads'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '54249ef0-23cc-468e-ae5e-b5dd76028baf',
        'question_ref': 'ENV-007',
        'question_text': 'How are development and testing environments provisioned?',
        'question_description': 'Select the approach that best represents environment provisioning.',
        'section_key': 'environment_information',
        'subsection_key': 'application_environments',
        'display_order': 70,
        'answer_type': 'select',
        'answer_options_json': ['Automatically using infrastructure as code', 'Automatically through a cloud or internal platform', 'Using scripts', 'Semi-manually', 'Manually', 'Other'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '1edae358-af31-4776-a107-6387d4c21943',
        'question_ref': 'ENV-008',
        'question_text': 'How consistent are development, testing, pre-production, and production environments?',
        'question_description': 'Evaluate configuration, versions, infrastructure, and deployment consistency.',
        'section_key': 'environment_information',
        'subsection_key': 'application_environments',
        'display_order': 80,
        'answer_type': 'select',
        'answer_options_json': ['Fully consistent', 'Mostly consistent', 'Partially consistent', 'Significantly different', 'Not evaluated'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'bac95907-789d-4c88-8c19-3afbd68408e8',
        'question_ref': 'ENV-009',
        'question_text': 'Which container and orchestration platforms are used?',
        'question_description': 'Select all container and orchestration technologies currently used.',
        'section_key': 'environment_information',
        'subsection_key': 'containers_and_orchestration',
        'display_order': 90,
        'answer_type': 'multi_select',
        'answer_options_json': ['Kubernetes', 'OpenShift', 'Docker', 'Amazon EKS', 'Azure Kubernetes Service', 'Google Kubernetes Engine', 'VMware Tanzu', 'No container platform', ],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '341ebd59-b7d6-4776-97f5-35038af847bf',
        'question_ref': 'ENV-010',
        'question_text': 'How is test data prepared and managed?',
        'question_description': 'Select the approach that best represents the current test-data process.',
        'section_key': 'environment_information',
        'subsection_key': 'test_data_management',
        'display_order': 100,
        'answer_type': 'select',
        'answer_options_json': ['Dedicated test-data management solution', 'Automatically generated synthetic data', 'Masked production data', 'Manually prepared test data', 'Direct production-data copies', 'No formally defined process'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'f436d0ee-82e0-4eb1-a01f-001090ffb899',
        'question_ref': 'ENV-011',
        'question_text': 'Which tools are used for test-data management?',
        'question_description': 'Select all dedicated tools or approaches used to manage test data.',
        'section_key': 'environment_information',
        'subsection_key': 'test_data_management',
        'display_order': 110,
        'answer_type': 'multi_select',
        'answer_options_json': ['OpenText Data Express', 'Broadcom Test Data Manager', 'Delphix', 'Informatica', 'IBM Optim', 'In-house solution', 'Scripts', 'No dedicated tool', ],
        'answer_unit_json': None,
        'dependency_json': {'question_ref': 'ENV-010', 'operator': 'not_equals', 'value': 'No formally defined process'},
        'visibility_condition_json': {'question_ref': 'ENV-010', 'operator': 'not_equals', 'value': 'No formally defined process'},
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '2369fb3f-860d-434d-a7a3-f7ba2c1cceec',
        'question_ref': 'ENV-012',
        'question_text': 'Which deployment targets are used?',
        'question_description': 'Select all infrastructure and platform targets used for application deployment.',
        'section_key': 'environment_information',
        'subsection_key': 'deployment_targets',
        'display_order': 120,
        'answer_type': 'multi_select',
        'answer_options_json': ['Physical servers', 'Virtual machines', 'Containers', 'Kubernetes clusters', 'Serverless platforms', 'Mainframe', 'Mobile application stores', 'SaaS platforms' ],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '9096d7e1-ef0a-43eb-bbed-a4b9ab636271',
        'question_ref': 'FIN-001',
        'question_text': 'How many working days are available per year?',
        'question_description': 'Use the company or country standard.',
        'section_key': 'financial_information',
        'subsection_key': 'work_calendar',
        'display_order': 10,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'c99eef67-8146-4ef2-90d6-aa8a1e7993fc',
        'question_ref': 'FIN-002',
        'question_text': 'How many working hours are included in a standard working day?',
        'question_description': 'Enter the standard daily working hours.',
        'section_key': 'financial_information',
        'subsection_key': 'work_calendar',
        'display_order': 20,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'd8c4df1d-d9a8-4ce8-a561-9b04893b73bb',
        'question_ref': 'FIN-003',
        'question_text': 'How many working weeks are included in one year?',
        'question_description': 'Enter the standard number of working weeks.',
        'section_key': 'financial_information',
        'subsection_key': 'work_calendar',
        'display_order': 30,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '741b6a12-5eac-414a-b703-65626c3e50a1',
        'question_ref': 'FIN-004',
        'question_text': 'How many working days are included in a standard working week?',
        'question_description': 'Enter the standard number of working days.',
        'section_key': 'financial_information',
        'subsection_key': 'work_calendar',
        'display_order': 40,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'aea33691-eff1-43f1-841f-6e7581844702',
        'question_ref': 'FIN-005',
        'question_text': 'What is the average number of holidays and absence days per FTE each year?',
        'question_description': 'Include annual leave and average absence days.',
        'section_key': 'financial_information',
        'subsection_key': 'work_calendar',
        'display_order': 50,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'cbfacfe8-6dd2-4961-aa60-bdad82bb71cf',
        'question_ref': 'FIN-006',
        'question_text': 'How are application delivery FTEs distributed?',
        'question_description': 'Provide the number of local, nearshore or offshore, and external FTEs.',
        'section_key': 'financial_information',
        'subsection_key': 'resource_distribution',
        'display_order': 60,
        'answer_type': 'multi_select',
        'answer_options_json': ['local ftes', 'nearshore offshore_ftes', 'external ftes'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'e94f2a5a-930b-48b3-8ff1-594dc2c18cfe',
        'question_ref': 'FIN-007',
        'question_text': 'How many FTEs are dedicated to software development?',
        'question_description': 'Include internal and external software development resources.',
        'section_key': 'financial_information',
        'subsection_key': 'resource_distribution',
        'display_order': 70,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '32ab361e-2067-4cd8-94bf-f8d18b8c8bcd',
        'question_ref': 'FIN-008',
        'question_text': 'How many FTEs are dedicated to functional testing and quality assurance?',
        'question_description': 'Include manual testers, automation engineers, and QA leads.',
        'section_key': 'financial_information',
        'subsection_key': 'resource_distribution',
        'display_order': 80,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '56b0b14e-50e9-48f7-9024-3c82392ed134',
        'question_ref': 'FIN-009',
        'question_text': 'How many FTEs are dedicated to performance testing, analysis, and optimization?',
        'question_description': 'Include performance engineers and specialists involved in analysis or tuning.',
        'section_key': 'financial_information',
        'subsection_key': 'resource_distribution',
        'display_order': 90,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '9d92d14c-1d1d-4efd-8dc6-d04222be11c1',
        'question_ref': 'FIN-010',
        'question_text': 'How many FTEs are dedicated to CI/CD, DevOps, and release management?',
        'question_description': 'Include DevOps engineers, platform engineers, and release managers.',
        'section_key': 'financial_information',
        'subsection_key': 'resource_distribution',
        'display_order': 100,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'ee36265c-b454-4b65-be93-69045bdf0fa0',
        'question_ref': 'FIN-011',
        'question_text': 'How many defects are detected in production each year?',
        'question_description': 'Enter the annual number of production defects.',
        'section_key': 'financial_information',
        'subsection_key': 'quality_costs',
        'display_order': 110,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '16f432b2-866c-43ac-9396-edebe59838f1',
        'question_ref': 'FIN-012',
        'question_text': 'How many production releases fail or require rollback each year?',
        'question_description': 'Include failed deployments, emergency rollbacks, and releases requiring immediate hotfixes.',
        'section_key': 'financial_information',
        'subsection_key': 'release_costs',
        'display_order': 120,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'ae0a0092-903e-44be-b6c9-a8ee8b4581e1',
        'question_ref': 'FIN-013',
        'question_text': 'What is the average time spent triaging a reported application defect?',
        'question_description': 'Provide the average elapsed triage time.',
        'section_key': 'financial_information',
        'subsection_key': 'quality_costs',
        'display_order': 130,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': ['Minutes', 'Hours', 'Days'],
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '69c95583-cdee-45bb-995f-363ba86b5897',
        'question_ref': 'FIN-014',
        'question_text': 'What is the average time required to correct and validate a production defect?',
        'question_description': 'Provide the average elapsed resolution and validation time.',
        'section_key': 'financial_information',
        'subsection_key': 'quality_costs',
        'display_order': 140,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': ['Hours', 'Days', 'Weeks'],
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'a2436423-1325-41f1-ba14-7ce214721a8b',
        'question_ref': 'FIN-015',
        'question_text': 'What percentage of delivery capacity is spent on corrective work and rework?',
        'question_description': 'Estimate the proportion of total delivery capacity used for corrections and repeated work.',
        'section_key': 'financial_information',
        'subsection_key': 'productivity_and_rework',
        'display_order': 150,
        'answer_type': 'select',
        'answer_options_json': ['Less than 10%', '10–25%', '26–50%', 'More than 50%', 'Unknown'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '6f2bebbc-839c-4f90-9c18-6895c99ed70e',
        'question_ref': 'FIN-016',
        'question_text': 'What is the estimated cost per hour of a major application incident?',
        'question_description': 'Include downtime, lost revenue, SLA penalties, support effort, technical correction, and customer impact.',
        'section_key': 'financial_information',
        'subsection_key': 'incident_costs',
        'display_order': 160,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': ['EUR'],
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'e986613e-f8e8-417f-9309-bc74b9881ca1',
        'question_ref': 'FIN-017',
        'question_text': 'What is the estimated average cost of a failed production release?',
        'question_description': 'Include investigation, correction, rollback, additional testing, support activities, and operational impact.',
        'section_key': 'financial_information',
        'subsection_key': 'release_costs',
        'display_order': 170,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': ['EUR'],
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'a7c88e14-8d26-4a2c-9e9d-042f7617c6f3',
        'question_ref': 'FIN-018',
        'question_text': 'What is the total annual cost of ADM tools and platforms?',
        'question_description': 'Include licences, subscriptions, maintenance, hosting, support, and managed services.',
        'section_key': 'financial_information',
        'subsection_key': 'adm_tool_costs',
        'display_order': 180,
        'answer_type': 'number',
        'answer_options_json': None,
        'answer_unit_json': ['EUR'],
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '3979b851-fd22-4961-b085-082b93c9b8b4',
        'question_ref': 'FIN-019',
        'question_text': 'What are the main causes of application delivery rework?',
        'question_description': 'Select all major causes of repeated or corrective work.',
        'section_key': 'financial_information',
        'subsection_key': 'productivity_and_rework',
        'display_order': 190,
        'answer_type': 'multi_select',
        'answer_options_json': ['Requirements detected or clarified too late',
                                 'Requirements changing during development', 
                                 'Insufficient functional testing', 
                                 'Insufficient performance testing', 
                                 'Defects detected too late', 
                                 'Differences between environments', 
                                 'Manual deployment errors', 
                                 'Poor communication between teams', 
                                 'Lack of end-to-end traceability', 
                                 'Insufficient test data', 
                                 'Limited automation', ''
                                 'Requirements detected or clarified too late',
'Requirements changing during development',
'Insufficient functional testing',
'Insufficient performance testing',
'Defects detected too late',
'Differences between environments',
'Manual deployment errors',
'Poor communication between teams',
'Lack of end-to-end traceability',
'Insufficient test data',
'Limited automation',
'Late security issues or vulnerabilities detected',
'Integration issues between systems or components',
'Infrastructure or configuration issues',
'Database or schema changes discovered late',
'Deployment or release process issues',
'Unclear or incomplete acceptance criteria',
'Dependency or third-party component issues',
'Incomplete impact analysis of changes',
'Inadequate documentation',
'Frequent scope changes',
'Insufficient environment provisioning',
'Unexpected production issues',
'Rollback or recovery issues',
'Inconsistent coding or development practices',
'Insufficient monitoring and observability'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': 'fa17ebbc-02ba-4a10-8a44-92eda5c3ad47',
        'question_ref': 'FIN-020',
        'question_text': 'Are formal policies in place to reduce application delivery costs?',
        'question_description': 'Indicate whether cost-reduction policies are defined and actively applied.',
        'section_key': 'financial_information',
        'subsection_key': 'cost_governance',
        'display_order': 200,
        'answer_type': 'select',
        'answer_options_json': ['Yes', 'Partially', 'Planned', 'No'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
    {
        'uid': '9daaeef9-d75a-424b-974b-d3adaac92c72',
        'question_ref': 'FIN-021',
        'question_text': 'What are the main expected benefits of improving ADM?',
        'question_description': 'Select all objectives expected from the ADM improvement programme.',
        'section_key': 'financial_information',
        'subsection_key': 'expected_benefits',
        'display_order': 210,
        'answer_type': 'multi_select',
        'answer_options_json': ['Reduce time to market', 'Reduce production defects', 'Reduce failed releases', 'Reduce testing costs', 'Reduce manual effort', 'Increase test automation', 'Improve team productivity', 'Improve end-to-end traceability', 'Improve application quality', 'Improve release predictability', 'Improve collaboration', 'Improve regulatory compliance', 'Improve customer satisfaction', 'Reduce overall development costs',
'Reduce maintenance costs',
'Improve application security',
'Improve risk management',
'Improve incident response',
'Improve system maintainability',
'Improve scalability',
'Improve visibility into delivery processes',
'Improve decision-making through better metrics',
'Reduce technical debt',
'Improve release frequency',
'Increase business agility'],
        'answer_unit_json': None,
        'dependency_json': None,
        'visibility_condition_json': None,
        'is_required': True,
        'is_active': True,
    },
]

def seed_adm_assessment_questions(session=None) -> None:
    """Insert or update every question from SEED_QUESTIONS into the database."""
    owns_session = session is None
    session = session or SessionLocal()
    try:
        inserted = 0
        updated = 0
        for payload in SEED_QUESTIONS:
            existing = (
                session.query(AdmAssessmentQuestion)
                .filter(AdmAssessmentQuestion.question_ref == payload["question_ref"])
                .one_or_none()
            )
            if existing:
                for key, value in payload.items():
                    if key == "uid":
                        continue  # never overwrite the primary key of an existing row
                    setattr(existing, key, value)
                existing.updated_at = datetime.now(timezone.utc)
                updated += 1
            else:
                session.add(AdmAssessmentQuestion(**payload))
                inserted += 1

        session.commit()
        print(f"adm_assessment_question seed complete: {inserted} inserted, {updated} updated.")
    except Exception:
        session.rollback()
        raise
    finally:
        if owns_session:
            session.close()


if __name__ == "__main__":
    seed_adm_assessment_questions()